### ISSUE TITLE
Versions is not taken into account in config

### ISSUE THREAD

**Issue by Yaya-Cout** [BloomyInDev/NumworksVersionChecker#1]
In the config file, there is a list called `versions` which should contain the release channels to watch.
However, the `stable` channel is hardcoded in the code, so you can't watch the beta channel.

What I would like to see would be to be able to watch multiple channels without bug.

**Comment by BloomyInDev** [comment]
I fixed it in 9bd33a885486b03ec9c6805e9349a33814bc1a0c

**Comment by BloomyInDev** [comment]
Deployed on docker hub
